package com.agentgenia.android.model

object ConnectorCatalog {
    val all = listOf(
        c("google-workspace", "Google Workspace", "Trabajo", "Gmail, Drive, Calendar, Contacts y Sheets"),
        c("slack", "Slack", "Trabajo", "Canales, mensajes y coordinación de equipo"),
        c("notion", "Notion", "Trabajo", "Páginas, bases de datos y conocimiento"),
        c("salesforce", "Salesforce", "Ventas", "Cuentas, contactos y oportunidades"),
        c("microsoft-365", "Microsoft 365", "Trabajo", "Outlook, OneDrive, Calendar y Teams"),
        c("linkedin", "LinkedIn", "Ventas", "Contactos y relaciones profesionales"),
        c("zoom", "Zoom", "Trabajo", "Reuniones y seguimiento de llamadas"),
        c("github", "GitHub", "Desarrollo", "Repositorios, issues y pull requests"),
        c("jira", "Jira", "Desarrollo", "Proyectos, tickets y ciclos de trabajo"),
        c("linear", "Linear", "Desarrollo", "Issues, proyectos y ciclos de producto"),
        c("asana", "Asana", "Trabajo", "Proyectos, tareas y responsables"),
        c("clickup", "ClickUp", "Trabajo", "Tareas, documentos y seguimiento"),
        c("figma", "Figma", "Diseño", "Archivos, comentarios y entregables"),
        c("hubspot", "HubSpot", "Ventas", "Contactos, empresas y oportunidades"),
        c("canva", "Canva", "Diseño", "Diseños, plantillas y contenido de marca"),
        c("trello", "Trello", "Trabajo", "Tableros, listas y tarjetas"),
        c("monday-com", "monday.com", "Trabajo", "Tableros, proyectos y automatizaciones"),
        c("intercom", "Intercom", "Soporte", "Conversaciones y atención al cliente"),
        c("zendesk", "Zendesk", "Soporte", "Tickets y operaciones de soporte"),
        c("box", "Box", "Trabajo", "Archivos y colaboración empresarial"),
        c("dropbox", "Dropbox", "Trabajo", "Archivos y contenido compartido"),
        c("docusign", "DocuSign", "Trabajo", "Firmas y seguimiento de documentos"),
        c("calendly", "Calendly", "Trabajo", "Disponibilidad y reuniones"),
        c("loom", "Loom", "Trabajo", "Videos, transcripciones y equipo"),
        c("outreach", "Outreach", "Ventas", "Prospectos, secuencias y actividades"),
        c("salesloft", "Salesloft", "Ventas", "Cadencias y actividades de ventas"),
        c("apollo", "Apollo", "Ventas", "Personas, empresas y enriquecimiento"),
        c("clay", "Clay", "Ventas", "Tablas, enriquecimiento y prospección"),
        c("zoominfo", "ZoomInfo", "Ventas", "Contactos e inteligencia comercial"),
        c("nooks", "Nooks", "Ventas", "Marcador y productividad de ventas"),
        c("stripe", "Stripe", "Finanzas", "Clientes, pagos, facturas y suscripciones"),
        c("quickbooks", "QuickBooks", "Finanzas", "Contabilidad, facturas y gastos"),
        c("netsuite", "NetSuite", "Finanzas", "ERP, clientes y operaciones"),
        c("ramp", "Ramp", "Finanzas", "Tarjetas, gastos y proveedores"),
        c("workday", "Workday", "RR. HH.", "Personas, puestos y recursos humanos"),
        c("rippling", "Rippling", "RR. HH.", "Empleados, nómina y aplicaciones"),
        c("ashby", "Ashby", "RR. HH.", "Candidatos, vacantes y contratación"),
        c("greenhouse", "Greenhouse", "RR. HH.", "Candidatos, entrevistas y vacantes"),
        c("vercel", "Vercel", "Desarrollo", "Proyectos, deployments, dominios y logs"),
        c("tableau", "Tableau", "Datos", "Fuentes, workbooks y visualizaciones"),
        c("hex", "Hex", "Datos", "Proyectos, notebooks y análisis"),
        c("amplitude", "Amplitude", "Datos", "Analítica de producto, eventos y cohortes"),
        c("mixpanel", "Mixpanel", "Datos", "Eventos, funnels y retención"),
        c("snowflake", "Snowflake", "Datos", "Warehouses, bases y consultas"),
        c("databricks", "Databricks", "Datos", "Lakehouse, notebooks y jobs"),
        c("mailchimp", "Mailchimp", "Marketing", "Audiencias, campañas y automatizaciones"),
        c("shopify", "Shopify", "Comercio", "Catálogo y contexto de tienda"),
        c("tiendanube", "Tiendanube", "Comercio", "Catálogo y contexto de tienda"),
        c("woocommerce", "WooCommerce", "Comercio", "Productos y WordPress Commerce"),
    )

    private fun c(id: String, name: String, category: String, summary: String) =
        ConnectorDefinition(id, name, category, summary)
}
