allowBuilds:
  '@google/genai': false
  '@injaneity/pi-computer-use': true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true
patchedDependencies:
  pi-chrome@0.15.46: patches/pi-chrome@0.15.46.patch
