-- Agent Genia keeps server-owned identities, encrypted provider keys, usage,
-- and Stripe entitlements in a private schema.  It is intentionally not
-- exposed through Supabase's Data API.
create schema if not exists agentgenia;

revoke all on schema agentgenia from public, anon, authenticated;

create table if not exists agentgenia.users (
  id text primary key,
  name text,
  email text,
  api_key_hash text unique not null,
  subscription_id text,
  tier text not null default 'free' check (tier in ('free', 'basic', 'pro')),
  created_at double precision not null
);

create table if not exists agentgenia.go_subscriptions (
  id text primary key,
  api_key_enc bytea not null,
  key_id text not null,
  label text,
  source text not null default 'pool' check (source in ('pool', 'byok')),
  status text not null default 'available'
    check (status in ('available', 'assigned', 'revoked')),
  assigned_user_id text references agentgenia.users(id) on delete set null,
  note text,
  created_at double precision not null
);

alter table agentgenia.users
  drop constraint if exists users_subscription_fk;
alter table agentgenia.users
  add constraint users_subscription_fk foreign key (subscription_id)
  references agentgenia.go_subscriptions(id) on delete set null
  deferrable initially deferred;

create table if not exists agentgenia.usage_events (
  id bigint generated by default as identity primary key,
  user_id text not null references agentgenia.users(id) on delete cascade,
  subscription_id text not null references agentgenia.go_subscriptions(id) on delete cascade,
  model text,
  endpoint text,
  input_tokens integer,
  output_tokens integer,
  cached_read_tokens integer,
  cached_write_tokens integer,
  estimated_cost_usd double precision not null default 0,
  status integer,
  created_at double precision not null
);

create table if not exists agentgenia.account_identities (
  id text primary key,
  user_id text not null references agentgenia.users(id) on delete cascade,
  provider text not null,
  subject text not null,
  email text not null,
  email_verified integer not null default 0 check (email_verified in (0, 1)),
  name text,
  picture text,
  created_at double precision not null,
  updated_at double precision not null,
  unique(provider, subject)
);

create table if not exists agentgenia.account_sessions (
  id text primary key,
  account_id text not null references agentgenia.account_identities(id) on delete cascade,
  device_id text not null,
  access_token_hash text unique not null,
  refresh_token_hash text unique not null,
  access_expires_at double precision not null,
  refresh_expires_at double precision not null,
  revoked_at double precision,
  created_at double precision not null
);

create table if not exists agentgenia.billing_customers (
  user_id text primary key references agentgenia.users(id) on delete cascade,
  stripe_customer_id text unique not null,
  created_at double precision not null,
  updated_at double precision not null
);

create table if not exists agentgenia.billing_subscriptions (
  stripe_subscription_id text primary key,
  user_id text not null references agentgenia.users(id) on delete cascade,
  tier text not null check (tier in ('basic', 'pro')),
  stripe_price_id text,
  status text not null,
  cancel_at_period_end integer not null default 0 check (cancel_at_period_end in (0, 1)),
  current_period_end bigint,
  updated_at double precision not null
);

create table if not exists agentgenia.stripe_events (
  event_id text primary key,
  event_type text not null,
  processed_at double precision not null
);

create table if not exists agentgenia.kv (
  k text primary key,
  v text
);

create index if not exists idx_users_subscription
  on agentgenia.users(subscription_id);
create unique index if not exists uniq_user_subscription
  on agentgenia.users(subscription_id) where subscription_id is not null;
create unique index if not exists uniq_go_subscription_user
  on agentgenia.go_subscriptions(assigned_user_id)
  where assigned_user_id is not null;
create index if not exists idx_subs_status
  on agentgenia.go_subscriptions(status, created_at);
create index if not exists idx_usage_user_time
  on agentgenia.usage_events(user_id, created_at);
create index if not exists idx_usage_sub_time
  on agentgenia.usage_events(subscription_id, created_at);
create index if not exists idx_account_identity_user
  on agentgenia.account_identities(user_id);
create index if not exists idx_account_session_account
  on agentgenia.account_sessions(account_id);
create index if not exists idx_account_session_refresh
  on agentgenia.account_sessions(refresh_token_hash);
create index if not exists idx_billing_subscription_user
  on agentgenia.billing_subscriptions(user_id, updated_at desc);
create index if not exists idx_billing_subscription_status
  on agentgenia.billing_subscriptions(status);

insert into agentgenia.kv(k, v) values ('schema_version', '4')
on conflict (k) do update set v = excluded.v;

-- Defense in depth: even if this schema is accidentally added to the Data API,
-- no browser-facing role can read or mutate these server-owned records.
alter table agentgenia.users enable row level security;
alter table agentgenia.go_subscriptions enable row level security;
alter table agentgenia.usage_events enable row level security;
alter table agentgenia.account_identities enable row level security;
alter table agentgenia.account_sessions enable row level security;
alter table agentgenia.billing_customers enable row level security;
alter table agentgenia.billing_subscriptions enable row level security;
alter table agentgenia.stripe_events enable row level security;
alter table agentgenia.kv enable row level security;

revoke all on all tables in schema agentgenia from public, anon, authenticated;
revoke all on all sequences in schema agentgenia from public, anon, authenticated;
alter default privileges in schema agentgenia
  revoke all on tables from public, anon, authenticated;
alter default privileges in schema agentgenia
  revoke all on sequences from public, anon, authenticated;
